// demo/svelte/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import {
    FetchPokemonDetailCommand,
    PokemonSelectedEvent,
    PokemonInspectedEvent,
    DeployToBattleCommand,
    SEED_POKEMON_LIST,
    AddTeamMemberSchemaCommand,
  } from "@demo/shared";
  import type { PokemonDetail } from "@demo/shared";
  import { Result } from "@collidor/result";

  export let busService: any;

  let currentPokemon: PokemonDetail = SEED_POKEMON_LIST[3]; // Pikachu default
  let isLoading = false;
  let statusMessage: string | null = null;
  let isErrorMessage = false;
  let unsubs: Array<() => void> = [];

  onMount(() => {
    const handleLoadPokemon = async (pokemon: any) => {
      if (!pokemon?.id) return;
      isLoading = true;
      try {
        const res = await busService.commandBus.execute(
          new FetchPokemonDetailCommand({ idOrName: pokemon.id })
        );

        if (Result.isResult(res) && res.success) {
          currentPokemon = res.value;
        } else if (!res.success) {
          console.error("Failed to fetch detail:", res.error);
        }
      } catch (err) {
        console.error("Command execution error:", err);
      } finally {
        isLoading = false;
      }
    };

    const unsubSelect = busService.eventBus.on(PokemonSelectedEvent, handleLoadPokemon);
    const unsubInspect = busService.eventBus.on(PokemonInspectedEvent, handleLoadPokemon);

    unsubs.push(unsubSelect, unsubInspect);
  });

  onDestroy(() => {
    unsubs.forEach((u) => u());
  });

  async function handleAddToTeam() {
    isErrorMessage = false;
    statusMessage = "Adding to Angular Team via SchemaCommand...";
    try {
      const res = await busService.commandBus.execute(
        new AddTeamMemberSchemaCommand({
          pokemon: currentPokemon,
          level: 50,
        })
      );

      if (res && res.success) {
        statusMessage = `✓ ${currentPokemon.name} added to party!`;
      } else {
        isErrorMessage = true;
        statusMessage = `⚠ ${res?.message || "Failed to add to team"}`;
      }
    } catch (err: any) {
      isErrorMessage = true;
      statusMessage = `⚠ Command Error: ${err.message || String(err)}`;
    }

    setTimeout(() => {
      statusMessage = null;
      isErrorMessage = false;
    }, 3500);
  }

  async function handleDeployToBattle() {
    isErrorMessage = false;
    statusMessage = `Deploying ${currentPokemon.name} to Battle Arena...`;
    try {
      const res = await busService.commandBus.execute(
        new DeployToBattleCommand({ pokemon: currentPokemon })
      );
      if (Result.isResult(res) && res.success) {
        statusMessage = `⚔️ ${currentPokemon.name} deployed to Battle Arena!`;
      } else {
        isErrorMessage = true;
        statusMessage = `⚠ Deploy failed: ${res?.error || "Unknown error"}`;
      }
    } catch (err: any) {
      isErrorMessage = true;
      statusMessage = `⚠ Command Error: ${err.message || String(err)}`;
    }

    setTimeout(() => {
      statusMessage = null;
      isErrorMessage = false;
    }, 3500);
  }
</script>

<div class="svelte-root">
  <!-- Top bar -->
  <div class="header-bar">
    <span class="title">
      <span class="dot"></span>
      Svelte 5 Reactive Inspector
    </span>
    {#if isLoading}
      <span class="loading-tag">Loading via CommandBus...</span>
    {/if}
  </div>

  <!-- Hero Card -->
  <div class="hero-card">
    {#if statusMessage}
      <div class="toast {isErrorMessage ? 'toast-err' : 'toast-ok'}">
        {statusMessage}
      </div>
    {/if}

    <div class="art-container">
      <div class="glow"></div>
      <img
        src={currentPokemon.sprites.artwork}
        alt={currentPokemon.name}
        class="artwork"
      />
      <img
        src={currentPokemon.sprites.showdownFront}
        alt="{currentPokemon.name} showdown"
        class="showdown"
      />
    </div>

    <span class="id-tag">#{currentPokemon.id.toString().padStart(3, "0")}</span>
    <h3 class="name">{currentPokemon.name}</h3>
    <p class="genus">{currentPokemon.species.genus}</p>

    <!-- Type Pills -->
    <div class="types-row">
      {#each currentPokemon.types as t}
        <span class="type-badge type-{t}">{t}</span>
      {/each}
    </div>

    <!-- Action Buttons -->
    <div class="actions-grid">
      <button on:click={handleAddToTeam} class="btn-team" title="Send to Angular Team Builder via SchemaCommand">
        <span>+ Add to Team</span>
        <span class="subtext">Angular Microfrontend</span>
      </button>

      <button on:click={handleDeployToBattle} class="btn-battle" title="Deploy directly to Solid Battle Arena">
        <span>⚔️ Deploy Arena</span>
        <span class="subtext">Solid.js Microfrontend</span>
      </button>
    </div>

    <!-- Flavor Text -->
    <p class="flavor-text">
      "{currentPokemon.species.flavorText}"
    </p>

    <!-- Stats Bars -->
    <div class="stats-box">
      <div class="stat-line">
        <span>HP</span>
        <span class="val">{currentPokemon.stats.hp}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill hp" style="width: {Math.min(100, (currentPokemon.stats.hp / 150) * 100)}%"></div>
      </div>

      <div class="stat-line pt">
        <span>Attack</span>
        <span class="val">{currentPokemon.stats.attack}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill atk" style="width: {Math.min(100, (currentPokemon.stats.attack / 150) * 100)}%"></div>
      </div>

      <div class="stat-line pt">
        <span>Defense</span>
        <span class="val">{currentPokemon.stats.defense}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill def" style="width: {Math.min(100, (currentPokemon.stats.defense / 150) * 100)}%"></div>
      </div>

      <div class="stat-line pt">
        <span>Speed</span>
        <span class="val">{currentPokemon.stats.speed}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill spd" style="width: {Math.min(100, (currentPokemon.stats.speed / 150) * 100)}%"></div>
      </div>
    </div>

    <!-- Moves List preview -->
    <div class="moves-box">
      <span class="moves-label">Combat Moves</span>
      <div class="moves-row">
        {#each currentPokemon.moves.slice(0, 4) as m}
          <span class="move-pill">{m.name}</span>
        {/each}
      </div>
    </div>
  </div>
</div>

<style>
  :global(:root) {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color-scheme: dark;
  }
  :global(html), :global(body) {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    background: #090d16;
    color: #f1f5f9;
    font-size: 13px;
    overflow-x: hidden;
  }
  :global(body.light), :global(html.light body) {
    background: #f8fafc;
    color: #0f172a;
  }
  * { box-sizing: border-box; }

  .svelte-root {
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 8px;
    box-sizing: border-box;
    overflow-y: auto;
  }
  .header-bar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-bottom: 6px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.08);
    margin-bottom: 8px;
    font-size: 11px;
  }
  .title {
    font-weight: 700;
    color: #fb923c;
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: #fb923c;
    box-shadow: 0 0 8px #fb923c;
  }
  .loading-tag {
    font-size: 10px;
    color: #f43f5e;
    animation: pulse 1.5s infinite;
  }

  .hero-card {
    background: rgba(15, 23, 42, 0.5);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 12px;
    padding: 12px;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    position: relative;
  }

  .toast {
    position: absolute;
    top: 8px;
    left: 8px;
    right: 8px;
    padding: 6px 10px;
    border-radius: 6px;
    font-size: 11px;
    font-weight: 600;
    z-index: 20;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
  }
  .toast-ok { background: #059669; color: #ffffff; }
  .toast-err { background: #e11d48; color: #ffffff; }

  .art-container {
    position: relative;
    width: 120px;
    height: 120px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 4px;
  }
  .glow {
    position: absolute;
    inset: 0;
    background: radial-gradient(circle, rgba(251, 146, 60, 0.2) 0%, transparent 70%);
    border-radius: 50%;
  }
  .artwork {
    width: 110px;
    height: 110px;
    object-fit: contain;
    position: relative;
    z-index: 2;
    filter: drop-shadow(0 6px 12px rgba(0, 0, 0, 0.4));
  }
  .showdown {
    position: absolute;
    bottom: -2px;
    right: -2px;
    width: 38px;
    height: 38px;
    object-fit: contain;
    z-index: 3;
    filter: drop-shadow(0 2px 4px rgba(0, 0, 0, 0.5));
  }

  .id-tag {
    font-size: 10px;
    font-family: monospace;
    color: #64748b;
  }
  .name {
    margin: 2px 0;
    font-size: 16px;
    font-weight: 800;
    text-transform: capitalize;
    color: #ffffff;
  }
  .genus {
    margin: 0 0 6px 0;
    font-size: 11px;
    color: #94a3b8;
  }

  .types-row {
    display: flex;
    gap: 4px;
    margin-bottom: 10px;
  }

  /* Badges */
  :global(.type-badge) {
    display: inline-block;
    font-size: 9px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 2px 7px;
    border-radius: 9999px;
    color: #ffffff;
    text-shadow: 0 1px 2px rgba(0,0,0,0.5);
  }
  :global(.type-normal) { background: #9fa19f; }
  :global(.type-fire) { background: #e62829; }
  :global(.type-water) { background: #2980ef; }
  :global(.type-grass) { background: #3fa129; }
  :global(.type-electric) { background: #fac000; color: #1e293b; text-shadow: none; }
  :global(.type-ice) { background: #3dcef3; color: #0f172a; text-shadow: none; }
  :global(.type-fighting) { background: #ff8000; }
  :global(.type-poison) { background: #9141cb; }
  :global(.type-ground) { background: #915121; }
  :global(.type-flying) { background: #81b9ef; color: #0f172a; text-shadow: none; }
  :global(.type-psychic) { background: #ef4179; }
  :global(.type-bug) { background: #91a119; }
  :global(.type-rock) { background: #afa981; }
  :global(.type-ghost) { background: #704170; }
  :global(.type-dragon) { background: #5060e1; }
  :global(.type-steel) { background: #60a1b8; }
  :global(.type-fairy) { background: #ef70ef; }

  .actions-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
    width: 100%;
    margin-bottom: 10px;
  }
  .btn-team, .btn-battle {
    padding: 8px 6px;
    border-radius: 8px;
    border: none;
    cursor: pointer;
    font-size: 11px;
    font-weight: 700;
    color: #ffffff;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 2px;
    transition: transform 0.1s ease, filter 0.1s ease;
  }
  .btn-team {
    background: linear-gradient(135deg, #f97316, #e11d48);
    box-shadow: 0 2px 8px rgba(249, 115, 22, 0.3);
  }
  .btn-battle {
    background: linear-gradient(135deg, #06b6d4, #2563eb);
    box-shadow: 0 2px 8px rgba(6, 182, 212, 0.3);
  }
  .btn-team:hover, .btn-battle:hover { filter: brightness(1.1); transform: translateY(-1px); }
  .btn-team:active, .btn-battle:active { transform: translateY(0); }
  .subtext {
    font-size: 9px;
    opacity: 0.85;
    font-weight: 500;
  }

  .flavor-text {
    font-size: 11px;
    color: #cbd5e1;
    font-style: italic;
    background: rgba(0, 0, 0, 0.25);
    padding: 8px 10px;
    border-radius: 6px;
    border: 1px solid rgba(255, 255, 255, 0.05);
    text-align: left;
    width: 100%;
    margin: 0 0 10px 0;
  }

  .stats-box {
    width: 100%;
    font-family: monospace;
    font-size: 10px;
    text-align: left;
    margin-bottom: 10px;
  }
  .stat-line {
    display: flex;
    justify-content: space-between;
    color: #94a3b8;
    margin-bottom: 2px;
  }
  .stat-line.pt { margin-top: 4px; }
  .val { font-weight: 700; color: #ffffff; }
  .bar-track {
    width: 100%;
    height: 4px;
    background: rgba(255, 255, 255, 0.1);
    border-radius: 9999px;
    overflow: hidden;
  }
  .bar-fill { height: 100%; border-radius: 9999px; transition: width 0.4s ease; }
  .bar-fill.hp { background: #34d399; }
  .bar-fill.atk { background: #f43f5e; }
  .bar-fill.def { background: #38bdf8; }
  .bar-fill.spd { background: #fbbf24; }

  .moves-box {
    width: 100%;
    text-align: left;
  }
  .moves-label {
    font-size: 9px;
    text-transform: uppercase;
    font-weight: 700;
    color: #64748b;
    display: block;
    margin-bottom: 4px;
  }
  .moves-row {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
  }
  .move-pill {
    padding: 2px 6px;
    border-radius: 4px;
    background: rgba(255, 255, 255, 0.08);
    font-size: 10px;
    font-family: monospace;
    color: #cbd5e1;
    text-transform: capitalize;
  }

  @keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  }
</style>

// demo/react/src/App.tsx
import React, { useState, useEffect, useMemo, useCallback } from "react";
import {
  ALL_GEN1_SUMMARY_LIST,
  FetchPokemonListCommand,
  FilterChangedEvent,
  PokemonSelectedEvent,
  PokemonInspectedEvent,
  PokemonSummary,
  PokemonType,
} from "@demo/shared";
import type { EventBus } from "@collidor/event";
import type { AsyncCommandBus } from "@collidor/command";

interface AppProps {
  eventBus: EventBus;
  commandBus: AsyncCommandBus<any, any>;
}

const ALL_TYPES: PokemonType[] = [
  "normal", "fire", "water", "grass", "electric", "ice",
  "fighting", "poison", "ground", "flying", "psychic", "bug",
  "rock", "ghost", "dragon", "steel", "fairy"
];

export const App: React.FC<AppProps> = ({ eventBus, commandBus }) => {
  const [pokemonList, setPokemonList] = useState<PokemonSummary[]>(ALL_GEN1_SUMMARY_LIST);
  const [selectedId, setSelectedId] = useState<number>(25); // Pikachu
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [selectedType, setSelectedType] = useState<PokemonType | undefined>();
  const [currentPage, setCurrentPage] = useState<number>(1);
  const pageSize = 10;

  // Filter list
  const filteredList = useMemo(() => {
    const query = searchTerm.toLowerCase().trim();
    return pokemonList.filter((p) => {
      const matchName = !query || p.name.toLowerCase().includes(query) || p.id.toString() === query;
      const matchType = !selectedType || p.types.includes(selectedType);
      return matchName && matchType;
    });
  }, [pokemonList, searchTerm, selectedType]);

  const totalPages = Math.max(1, Math.ceil(filteredList.length / pageSize));

  // Paginated slice
  const paginatedList = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return filteredList.slice(start, start + pageSize);
  }, [filteredList, currentPage, pageSize]);

  // Reset page on filter change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, selectedType]);

  // Select Pokemon & emit over EventBus across PortChannel
  const handleSelect = useCallback((pokemon: PokemonSummary) => {
    setSelectedId(pokemon.id);
    eventBus.emit(new PokemonSelectedEvent(pokemon));
  }, [eventBus]);

  // Subscribe to external events
  useEffect(() => {
    // 1. Fetch live 151 list via CommandBus
    commandBus.execute(new FetchPokemonListCommand({ limit: 151 }))
      .then((res) => {
        if (res?.success && res.value?.length > 0) {
          setPokemonList(res.value);
        }
      })
      .catch(() => {});

    // 2. Listen to filter events from host search bar
    const unsubFilter = eventBus.on(FilterChangedEvent, (data: any) => {
      if (typeof data.search === "string") setSearchTerm(data.search);
      setSelectedType(data.selectedType);
    });

    // 3. Listen to selection & inspection updates from Svelte, Angular, Solid
    const syncSelection = (data: any) => {
      if (data?.id) {
        setSelectedId(data.id);
      }
    };

    const unsubSelect = eventBus.on(PokemonSelectedEvent, syncSelection);
    const unsubInspect = eventBus.on(PokemonInspectedEvent, syncSelection);

    return () => {
      unsubFilter();
      unsubSelect();
      unsubInspect();
    };
  }, [eventBus, commandBus]);

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", padding: "8px", boxSizing: "border-box" }}>
      {/* Header bar */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingBottom: "8px", borderBottom: "1px solid rgba(255,255,255,0.08)", marginBottom: "8px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "6px", fontSize: "11px", fontWeight: "700", color: "#38bdf8" }}>
          <span style={{ width: "8px", height: "8px", borderRadius: "50%", background: "#38bdf8", boxShadow: "0 0 8px #38bdf8" }}></span>
          React 18 Catalog
        </div>
        <div style={{ fontSize: "10px", fontFamily: "monospace", padding: "2px 8px", borderRadius: "4px", background: "rgba(56, 189, 248, 0.1)", border: "1px solid rgba(56, 189, 248, 0.25)", color: "#7dd3fc" }}>
          {filteredList.length} / 151 Pokémon
        </div>
      </div>

      {/* Local Filter Bar */}
      <div style={{ display: "flex", gap: "6px", marginBottom: "8px" }}>
        <div style={{ position: "relative", flex: 1 }}>
          <input
            type="text"
            placeholder="Search Pokémon..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            style={{
              width: "100%",
              boxSizing: "border-box",
              padding: "6px 24px 6px 10px",
              borderRadius: "6px",
              border: "1px solid rgba(255,255,255,0.15)",
              background: "rgba(15, 23, 42, 0.6)",
              color: "#ffffff",
              fontSize: "12px",
              outline: "none",
            }}
          />
          {searchTerm && (
            <button
              onClick={() => setSearchTerm("")}
              style={{
                position: "absolute",
                right: "6px",
                top: "50%",
                transform: "translateY(-50%)",
                background: "transparent",
                border: "none",
                color: "#94a3b8",
                cursor: "pointer",
                fontSize: "12px",
              }}
            >
              ✕
            </button>
          )}
        </div>

        <select
          value={selectedType || ""}
          onChange={(e) => setSelectedType(e.target.value ? (e.target.value as PokemonType) : undefined)}
          style={{
            padding: "6px 8px",
            borderRadius: "6px",
            border: "1px solid rgba(255,255,255,0.15)",
            background: "rgba(15, 23, 42, 0.8)",
            color: "#e2e8f0",
            fontSize: "11px",
            outline: "none",
            textTransform: "capitalize",
          }}
        >
          <option value="">All Types</option>
          {ALL_TYPES.map((t) => (
            <option key={t} value={t}>{t}</option>
          ))}
        </select>
      </div>

      {/* Scrollable Pokemon List */}
      <div style={{ flex: 1, overflowY: "auto", display: "flex", flexDirection: "column", gap: "6px", paddingRight: "4px" }}>
        {paginatedList.map((p) => {
          const isSelected = selectedId === p.id;
          return (
            <div
              key={p.id}
              onClick={() => handleSelect(p)}
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                padding: "6px 10px",
                borderRadius: "8px",
                cursor: "pointer",
                transition: "all 0.15s ease",
                background: isSelected ? "rgba(244, 63, 94, 0.18)" : "rgba(15, 23, 42, 0.4)",
                border: isSelected ? "1px solid rgba(244, 63, 94, 0.5)" : "1px solid rgba(255, 255, 255, 0.05)",
                userSelect: "none",
              }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                <div style={{
                  width: "36px",
                  height: "36px",
                  borderRadius: "6px",
                  background: "rgba(0, 0, 0, 0.3)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  border: "1px solid rgba(255, 255, 255, 0.05)",
                }}>
                  <img
                    src={p.sprites.thumbnail}
                    alt={p.name}
                    style={{ width: "32px", height: "32px", objectFit: "contain" }}
                    loading="lazy"
                  />
                </div>
                <div>
                  <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                    <span style={{ fontWeight: "700", textTransform: "capitalize", fontSize: "12px", color: isSelected ? "#f43f5e" : "#f1f5f9" }}>
                      {p.name}
                    </span>
                    <span style={{ fontSize: "10px", fontFamily: "monospace", color: "#64748b" }}>
                      #{p.id.toString().padStart(3, "0")}
                    </span>
                  </div>
                  <div style={{ display: "flex", gap: "4px", marginTop: "3px" }}>
                    {p.types.map((t) => (
                      <span key={t} className={`type-badge type-${t}`}>
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              <span style={{
                fontWeight: "700",
                fontSize: "12px",
                color: isSelected ? "#f43f5e" : "#475569",
              }}>
                →
              </span>
            </div>
          );
        })}

        {filteredList.length === 0 && (
          <div style={{ textAlign: "center", padding: "30px 10px", color: "#94a3b8", fontSize: "12px" }}>
            No Pokémon match your search.
          </div>
        )}
      </div>

      {/* Pagination Footer */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: "8px", borderTop: "1px solid rgba(255,255,255,0.08)", fontSize: "11px", userSelect: "none" }}>
        <span style={{ color: "#94a3b8" }}>
          Page {currentPage} of {totalPages}
        </span>
        <div style={{ display: "flex", gap: "4px" }}>
          <button
            onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
            disabled={currentPage <= 1}
            style={{
              padding: "3px 8px",
              borderRadius: "4px",
              background: "rgba(15, 23, 42, 0.8)",
              border: "1px solid rgba(255,255,255,0.1)",
              color: "#cbd5e1",
              cursor: currentPage <= 1 ? "not-allowed" : "pointer",
              opacity: currentPage <= 1 ? 0.3 : 1,
            }}
          >
            ◀
          </button>
          <button
            onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
            disabled={currentPage >= totalPages}
            style={{
              padding: "3px 8px",
              borderRadius: "4px",
              background: "rgba(15, 23, 42, 0.8)",
              border: "1px solid rgba(255,255,255,0.1)",
              color: "#cbd5e1",
              cursor: currentPage >= totalPages ? "not-allowed" : "pointer",
              opacity: currentPage >= totalPages ? 0.3 : 1,
            }}
          >
            ▶
          </button>
        </div>
      </div>
    </div>
  );
};
