// demo/showcase/src/components/DocViewer.tsx
import React, { useState } from "react";
import { busService } from "../services/busService";
import {
  FetchPokemonDetailCommand,
  PokemonSelectedEvent,
  SEED_POKEMON_LIST,
} from "@demo/shared";
import { Result } from "@collidor/result";
import { EventBus } from "@collidor/event";
import { CodeBlock } from "./CodeBlock";

interface CodeExample {
  id: string;
  title: string;
  description: string;
  code: string;
  actionLabel?: string;
  onAction?: () => Promise<string> | string;
}

interface DocSection {
  id: string;
  name: string;
  package: string;
  summary: string;
  examples: CodeExample[];
  apiTable: Array<{ item: string; type: string; description: string }>;
}

export const DocViewer: React.FC = () => {
  const [activeSectionId, setActiveSectionId] = useState("result");
  const [activeExampleIndex, setActiveExampleIndex] = useState(0);
  const [exampleOutputs, setExampleOutputs] = useState<Record<string, string>>({});

  const setOutput = (exampleId: string, output: string) => {
    setExampleOutputs((prev) => ({ ...prev, [exampleId]: output }));
  };

  const sections: DocSection[] = [
    {
      id: "result",
      name: "Result Monad & Composition",
      package: "@collidor/result",
      summary:
        "High-performance, realm-safe Result monad designed specifically for cross-context architectures. Eliminates cross-iframe instanceof bugs, preserves remote stack traces across Web Workers, and provides functional pipelines (pipe/pipeAsync) and monadic operations.",
      examples: [
        {
          id: "result-pipeline",
          title: "Pipelines (pipe & pipeAsync)",
          description:
            "Chain synchronous or asynchronous operations into a railway-oriented pipeline. Automatically short-circuits on the first failure without try/catch boilerplate.",
          code: `import { Result } from "@collidor/result";

// 1. Synchronous functional pipeline
const calculateBattleDamage = (basePower: number) =>
  Result.pipe(
    Result.ok(basePower),
    (power) => power > 0 ? power : Result.err("Invalid move power"),
    (power) => power * 1.5, // STAB modifier
    (power) => Math.round(power * 0.85) // Random variance
  );

const syncResult = calculateBattleDamage(90);
console.log("Sync Pipeline Output:", Result.unwrap(syncResult)); // 115

// 2. Asynchronous pipeline with mixed sync/async transforms
const pipelinePromise = await Result.pipeAsync(
  Result.ok({ pokemonId: 25, level: 50 }),
  async (data) => {
    // Simulated async stats calculation
    return { ...data, hp: data.level * 2 + 10 };
  },
  (data) => {
    return data.hp > 0 ? Result.ok(data) : Result.err("Fainted");
  }
);

console.log("Async Pipeline Output:", Result.unwrap(pipelinePromise));`,
          actionLabel: "Run Pipelines",
          onAction: async () => {
            const syncRes = Result.pipe(
              Result.ok(90),
              (power) => (power > 0 ? power : Result.err("Invalid power")),
              (power) => power * 1.5,
              (power) => Math.round(power * 0.85)
            );
            const asyncRes = await Result.pipeAsync(
              Result.ok({ pokemonId: 25, level: 50 }),
              async (data) => ({ ...data, hp: data.level * 2 + 10 }),
              (data) => Result.ok({ ...data, ready: true })
            );

            const out = `Sync: ${JSON.stringify(syncRes)} | Async: ${JSON.stringify(asyncRes)}`;
            setOutput("result-pipeline", out);
            busService.logTelemetry("result", "ResultPipelineExecuted", "DocViewer", { sync: syncRes, async: asyncRes });
            return out;
          },
        },
        {
          id: "result-monadic",
          title: "Monadic Operations (map & chain)",
          description:
            "Transform inner values with `map()` or compose Result-returning functions with `chain()` (monadic flatMap). Use `getOrElse()` to supply safe fallbacks.",
          code: `import { Result } from "@collidor/result";

interface Combatant {
  name: string;
  hp: number;
}

const findCombatant = (id: number): Result<Combatant, string> =>
  id === 25 ? Result.ok({ name: "Pikachu", hp: 100 }) : Result.err("Combatant not found");

const applyDamage = (c: Combatant, damage: number): Result<Combatant, string> =>
  c.hp > damage
    ? Result.ok({ ...c, hp: c.hp - damage })
    : Result.err(\`\${c.name} has fainted!\`);

// Monadic chaining: Result<A> -> (A -> Result<B>) -> Result<B>
const battleRound = findCombatant(25)
  .pipe((res) => Result.chain(res, (c) => applyDamage(c, 30)));

// Functor mapping: Result<B> -> (B -> C) -> Result<C>
const logMessage = Result.map(battleRound, (c) => \`\${c.name} remaining HP: \${c.hp}\`);

// Safe fallback: value or default
const finalStatus = Result.getOrElse(logMessage, "Battle error occurred");
console.log(finalStatus); // "Pikachu remaining HP: 70"`,
          actionLabel: "Test Monadic Chain",
          onAction: () => {
            const combatant = { name: "Pikachu", hp: 100 };
            const damaged = Result.chain(Result.ok<any, any>(combatant), (c: any) =>
              c.hp > 30 ? Result.ok({ ...c, hp: c.hp - 30 }) : Result.err({ message: "Fainted" })
            );
            const mapped = Result.map(damaged, (c: any) => `${c.name} has ${c.hp} HP`);
            const out = `Result.chain -> Result.map: "${Result.unwrap(mapped)}"`;
            setOutput("result-monadic", out);
            busService.logTelemetry("result", "ResultMonadicExecuted", "DocViewer", mapped);
            return out;
          },
        },
        {
          id: "result-crossframe",
          title: "Cross-Frame Error Hydration",
          description:
            "Standard `instanceof Error` fails across iframes and workers because Error prototypes reside in different execution realms. Result solves this structurally.",
          code: `import { Result } from "@collidor/result";

// 1. In Worker / Iframe: Error is serialized over MessagePort as a plain object
const serializedError = {
  message: "Remote database query timed out after 5000ms",
  stack: "Error: Remote database query timed out\\n    at queryWorker (worker.js:42:15)"
};

// 2. In Host Realm: Result.from() detects ErrorLike shape structurally
const res = Result.from(serializedError);
console.log(res.success); // false
console.log(Result.isResult(res)); // true (boundary-safe duck typing)

// 3. Result.unwrap() re-hydrates plain object into a true native Error instance
try {
  Result.unwrap(res);
} catch (nativeError) {
  console.log(nativeError instanceof Error); // true!
  console.log(nativeError.message); // "Remote database query timed out after 5000ms"
  console.log(nativeError.stack); // Includes "From Remote: ... worker.js:42"
}`,
          actionLabel: "Test Error Hydration",
          onAction: () => {
            const fakeRemoteError = {
              message: "Iframe worker calculation failed",
              stack: "RemoteStack: worker.js:89",
            };
            const res = Result.from(fakeRemoteError);
            let hydratedInfo = "";
            try {
              Result.unwrap(res);
            } catch (err: any) {
              hydratedInfo = `Hydrated Error: "${err.message}" (instanceof Error: ${err instanceof Error})`;
            }
            setOutput("result-crossframe", hydratedInfo);
            busService.logTelemetry("result", "ResultErrorHydrationTested", "DocViewer", { hydratedInfo });
            return hydratedInfo;
          },
        },
        {
          id: "result-batch",
          title: "Batch Aggregation (combine & try)",
          description:
            "Combine multiple Results into a single Result with `combine()` (like Promise.all for Results), and safely wrap throwing third-party calls with `Result.try()`.",
          code: `import { Result } from "@collidor/result";

// 1. combine() aggregates an array of Results; fails fast on first error
const teamChecks = [
  Result.ok({ slot: 1, name: "Pikachu", valid: true }),
  Result.ok({ slot: 2, name: "Charizard", valid: true }),
  Result.ok({ slot: 3, name: "Blastoise", valid: true }),
];

const batchResult = Result.combine(teamChecks);
if (batchResult.success) {
  console.log(\`All \${batchResult.value.length} members validated!\`);
}

// 2. Result.try() encapsulates throwing sync operations
const jsonResult = Result.try(() => JSON.parse('{ "invalid": json }'));
console.log(jsonResult.success); // false
console.log(jsonResult.error.message); // SyntaxError message without crashing app!

// 3. Result.fromPromise() converts async rejections
const apiResult = await Result.fromPromise(fetch("/api/non-existent"));`,
          actionLabel: "Test Batch & Try",
          onAction: () => {
            const r1 = Result.ok("Slot 1 Ready");
            const r2 = Result.ok("Slot 2 Ready");
            const combined = Result.combine([r1, r2]);
            const safeTry = Result.try(() => {
              throw new Error("Simulated controlled parse exception");
            });
            const out = `combine: [${combined.value?.join(", ")}] | try caught: "${safeTry.error?.message}"`;
            setOutput("result-batch", out);
            busService.logTelemetry("result", "ResultBatchTested", "DocViewer", { combined, safeTry });
            return out;
          },
        },
      ],
      apiTable: [
        { item: "Result.ok(value)", type: "Static", description: "Constructs an Ok<T> result with success: true and value." },
        { item: "Result.err(error)", type: "Static", description: "Constructs an Err<E> result with success: false and error payload." },
        { item: "Result.none()", type: "Static", description: "Creates a failure Result with null error ({ success: false, error: null })." },
        { item: "Result.isResult(val)", type: "Static", description: "Boundary-safe structural duck-typing check (cross-realm safe)." },
        { item: "Result.from(valOrError)", type: "Static", description: "Converts value or ErrorLike object into Ok or Err automatically." },
        { item: "Result.fromPromise(p)", type: "Static", description: "Wraps a Promise, resolving to Ok or catching rejection into Err." },
        { item: "Result.try(fn)", type: "Static", description: "Executes a throwing sync function, wrapping throws in Result.err." },
        { item: "Result.unwrap(result)", type: "Static", description: "Returns value or throws error re-hydrated with remote stack trace." },
        { item: "Result.map(result, fn)", type: "Static", description: "Transforms value if successful; leaves error untouched." },
        { item: "Result.chain(result, fn)", type: "Static", description: "Monadic bind/flatMap: chains another Result-returning function." },
        { item: "Result.getOrElse(res, def)", type: "Static", description: "Returns result value or fallback default if failed." },
        { item: "Result.pipe(res, ...ops)", type: "Static", description: "Synchronous functional pipeline with short-circuiting on failure." },
        { item: "Result.pipeAsync(res, ...ops)", type: "Static", description: "Asynchronous pipeline supporting mixed sync/async transforms." },
        { item: "Result.combine([r1, r2, ...])", type: "Static", description: "Combines an array of Results into a Result of values array." },
      ],
    },
    {
      id: "command",
      name: "Command Bus",
      package: "@collidor/command",
      summary:
        "Type-safe, synchronous and asynchronous command routing with streaming, plugins, and HTTP / PortChannel extensions.",
      examples: [
        {
          id: "command-basic",
          title: "Command Bus Dispatch & Handlers",
          description: "Define strongly typed input/output commands and register handlers with full inference.",
          code: `import { Command, CommandBus } from "@collidor/command";

class FetchPokemonCommand extends Command<{ id: number }, { name: string; type: string }> {}

const bus = new CommandBus();

bus.register(FetchPokemonCommand, async (cmd) => {
  return { name: "Pikachu", type: "electric" };
});

const result = await bus.execute(new FetchPokemonCommand({ id: 25 }));
console.log(result.name); // "Pikachu"`,
          actionLabel: "Execute Command",
          onAction: async () => {
            const res = await busService.commandBus.execute(new FetchPokemonDetailCommand({ idOrName: 25 }));
            const out = res.success ? `Loaded ${res.value.name} (#${res.value.id})` : `Error: ${res.error}`;
            setOutput("command-basic", out);
            return out;
          },
        },
        {
          id: "command-portchannel",
          title: "Cross-Frame IPC (PortChannelPlugin)",
          description: "Execute commands across iframes and workers using PortChannelPlugin with handshake readiness.",
          code: `import { AsyncCommandBus, PortChannelPlugin } from "@collidor/command";

const plugin = new PortChannelPlugin({
  commandTimeout: 10000,
  ackTimeout: 5000,
});

const bus = new AsyncCommandBus({ plugin });

// Await remote iframe readiness before executing
await bus.waitFor(GetTeamCommand, { timeout: 5000 });
const team = await bus.execute(new GetTeamCommand());`,
          actionLabel: "Test Remote Bus",
          onAction: async () => {
            const out = `PortChannelPlugin active on Host. Connected iframes: Angular (team) & Solid (battle).`;
            setOutput("command-portchannel", out);
            return out;
          },
        },
      ],
      apiTable: [
        { item: "register(Command, handler)", type: "Method", description: "Registers a synchronous or asynchronous command handler." },
        { item: "execute(command, context?)", type: "Method", description: "Executes a command instance with typed return inference." },
        { item: "stream(command, callback)", type: "Method", description: "Executes a generator or stream handler with callback events." },
        { item: "waitFor(Command, options?)", type: "Method", description: "Awaits remote command availability across PortChannel." },
        { item: "PortChannelPlugin", type: "Class", description: "Plugin bridging command dispatch over MessagePort interfaces." },
      ],
    },
    {
      id: "event",
      name: "Event Bus & PortChannel",
      package: "@collidor/event",
      summary:
        "High-performance publish/subscribe messaging system with cross-context PortChannel routing over MessagePort, BroadcastChannel, and Workers.",
      examples: [
        {
          id: "event-basic",
          title: "Typed Pub/Sub Event Broadcast",
          description: "Publish strongly typed events to local and remote subscribers with optional AbortSignal teardown.",
          code: `import { Event, EventBus, PortChannel } from "@collidor/event";

class PokemonSelectedEvent extends Event<{ id: number; name: string }> {}

const channel = new PortChannel({ bufferTimeout: 5000 });
const bus = new EventBus({ channel });

bus.on(PokemonSelectedEvent, (data) => {
  console.log(\`Selected: \${data.name} (#\${data.id})\`);
});

bus.emit(new PokemonSelectedEvent({ id: 25, name: "pikachu" }));`,
          actionLabel: "Emit Selection",
          onAction: () => {
            const char = SEED_POKEMON_LIST.find((p) => p.name === "charmander")!;
            busService.eventBus.emit(new PokemonSelectedEvent(char));
            const out = `Emitted PokemonSelectedEvent for Charmander (#4)`;
            setOutput("event-basic", out);
            return out;
          },
        },
      ],
      apiTable: [
        { item: "on(Event, callback, signal?)", type: "Method", description: "Subscribes to an event with optional AbortSignal teardown." },
        { item: "emit(eventInstance, context?)", type: "Method", description: "Broadcasts an event instance to all local & remote subscribers." },
        { item: "addPort(port)", type: "Method", description: "Connects a MessagePortLike interface to the PortChannel bridge." },
        { item: "bufferTimeout", type: "Option", description: "Max ms events stay buffered waiting for a subscriber (default: 5000ms)." },
      ],
    },
    {
      id: "injector",
      name: "Dependency Injector",
      package: "@collidor/injector",
      summary:
        "Lightweight, hierarchical dependency injection container with class providers, factory providers, and token injection.",
      examples: [
        {
          id: "injector-basic",
          title: "Container & Token Resolution",
          description: "Register and resolve singletons, factories, and bus instances cleanly.",
          code: `import { Injector } from "@collidor/injector";
import { EventBus } from "@collidor/event";

const container = new Injector();
container.register(EventBus, new EventBus());

const bus = container.get(EventBus);
console.log(bus instanceof EventBus); // true`,
          actionLabel: "Inspect Injector",
          onAction: () => {
            const bus = busService.injector.get(EventBus);
            const out = `Resolved EventBus from Injector: ${bus ? "Success" : "Failed"}`;
            setOutput("injector-basic", out);
            return out;
          },
        },
      ],
      apiTable: [
        { item: "register(token, valueOrFactory)", type: "Method", description: "Binds a token to an instance or factory provider." },
        { item: "get(token)", type: "Method", description: "Resolves a registered dependency or throws if missing." },
        { item: "safeInject(token)", type: "Method", description: "Returns undefined instead of throwing if token is unregistered." },
      ],
    },
    {
      id: "schema-command",
      name: "Schema-Validated Commands",
      package: "@collidor/schema-command",
      summary:
        "Binds Zod runtime schemas to Command inputs and outputs, ensuring data crossing framework or network boundaries is guaranteed valid.",
      examples: [
        {
          id: "schema-basic",
          title: "Zod Contract Enforcement",
          description: "Enforce contract validation across iframe boundaries at runtime.",
          code: `import { schemaCommand } from "@collidor/schema-command";
import { z } from "zod";

const AddTeamMemberCommand = schemaCommand(
  z.object({
    pokemonId: z.number().int().positive(),
    nickname: z.string().max(12).optional(),
  }),
  z.object({
    success: z.boolean(),
    teamCount: z.number(),
  })
);`,
          actionLabel: "Verify Schemas",
          onAction: () => {
            const out = `AddTeamMemberSchemaCommand is active and validated by Zod schema across Angular and Solid.`;
            setOutput("schema-basic", out);
            return out;
          },
        },
      ],
      apiTable: [
        { item: "schemaCommand(inputSchema, outputSchema)", type: "Function", description: "Creates a strongly-typed Command class with Zod validation." },
        { item: "validateInput(data)", type: "Method", description: "Validates input payload against Zod schema prior to execution." },
      ],
    },
  ];

  const currentSection = sections.find((s) => s.id === activeSectionId) || sections[0];
  const currentExample = currentSection.examples[activeExampleIndex] || currentSection.examples[0];

  const handleSectionChange = (id: string) => {
    setActiveSectionId(id);
    setActiveExampleIndex(0);
  };

  return (
    <div className="max-w-6xl mx-auto py-6 flex flex-col md:flex-row gap-6">
      {/* Sidebar Navigation */}
      <div className="w-full md:w-64 shrink-0 space-y-1">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 px-3 py-2">
          Toolkit Modules
        </h3>
        {sections.map((sec) => (
          <button
            key={sec.id}
            onClick={() => handleSectionChange(sec.id)}
            className={`w-full text-left px-3.5 py-2.5 rounded-xl text-xs font-semibold transition flex items-center justify-between cursor-pointer ${
              activeSectionId === sec.id
                ? "bg-rose-500 text-white shadow-md font-bold"
                : "text-slate-700 dark:text-slate-400 hover:text-slate-950 dark:hover:text-white hover:bg-slate-200/70 dark:hover:bg-slate-900"
            }`}
          >
            <span>{sec.name}</span>
            <span className={`text-[10px] font-mono ${activeSectionId === sec.id ? "text-rose-100 font-bold" : "text-slate-500"}`}>
              {sec.package.replace("@collidor/", "")}
            </span>
          </button>
        ))}
      </div>

      {/* Main Content Area */}
      <div className="flex-1 space-y-6 min-w-0">
        <div className="glass-panel p-6 border-l-4 border-rose-500">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
            <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
              {currentSection.name}
            </h2>
            <code className="text-xs text-rose-700 dark:text-rose-400 bg-rose-50 dark:bg-rose-950/60 px-2.5 py-1 rounded-md border border-rose-200 dark:border-rose-500/20 font-mono font-bold">
              npm install {currentSection.package}
            </code>
          </div>
          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
            {currentSection.summary}
          </p>
        </div>

        {/* Example Selector Tabs */}
        {currentSection.examples.length > 1 && (
          <div className="flex items-center gap-2 border-b border-slate-200 dark:border-white/10 pb-2.5 overflow-x-auto">
            {currentSection.examples.map((ex, idx) => (
              <button
                key={ex.id}
                onClick={() => setActiveExampleIndex(idx)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition shrink-0 flex items-center gap-1.5 cursor-pointer ${
                  activeExampleIndex === idx
                    ? "bg-emerald-600 text-white shadow-sm font-bold"
                    : "bg-slate-100 dark:bg-slate-900/60 text-slate-700 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-800 border border-slate-200 dark:border-transparent"
                }`}
              >
                <span>{ex.title}</span>
              </button>
            ))}
          </div>
        )}

        {/* Active Example CodeBlock with Prism Highlight */}
        <div>
          <div className="mb-2.5">
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">{currentExample.title}</h3>
            <p className="text-xs text-slate-600 dark:text-slate-400 mt-0.5">{currentExample.description}</p>
          </div>

          <CodeBlock
            code={currentExample.code}
            language="typescript"
            title={`${currentSection.package} - ${currentExample.title}`}
            actionLabel={currentExample.actionLabel}
            onAction={currentExample.onAction}
            outputLog={exampleOutputs[currentExample.id]}
          />
        </div>

        {/* API Reference Table */}
        <div className="glass-panel p-6">
          <h3 className="text-sm font-bold text-slate-900 dark:text-white mb-3">API Reference</h3>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-200 dark:border-white/10 text-slate-600 dark:text-slate-400">
                  <th className="py-2.5 px-3 font-bold">Symbol</th>
                  <th className="py-2.5 px-3 font-bold">Kind</th>
                  <th className="py-2.5 px-3 font-bold">Description</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-white/5 font-mono">
                {currentSection.apiTable.map((api, idx) => (
                  <tr key={idx} className="hover:bg-slate-50/50 dark:hover:bg-white/[0.02] transition-colors">
                    <td className="py-2.5 px-3 text-rose-600 dark:text-rose-400 font-bold">{api.item}</td>
                    <td className="py-2.5 px-3 text-slate-500 dark:text-slate-400 font-medium">{api.type}</td>
                    <td className="py-2.5 px-3 font-sans text-slate-700 dark:text-slate-300">{api.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

// demo/showcase/src/components/DocViewer.vue
<script setup lang="ts">
import { ref } from "vue";
import CodeBlock from "./CodeBlock.vue";
import Callout from "./Callout.vue";
import { Result } from "@collidor/result";
import { EventBus } from "@collidor/event";
import { busService } from "../services/busService";

const emit = defineEmits<{
  (e: "launchDemo"): void;
}>();

const exampleOutputs = ref<Record<string, string>>({});

function setOutput(exampleId: string, output: string) {
  exampleOutputs.value = { ...exampleOutputs.value, [exampleId]: output };
}

// 1. Result Action
function runResultPipeline() {
  const res = Result.pipe(
    Result.ok(90),
    (power: number) => power * 1.5,
    (power: number) => Math.round(power * 0.85)
  );
  const out = `Pipeline computed damage: ${Result.unwrap(res)} (STAB + random variance)`;
  setOutput("result-pipeline", out);
  busService.logTelemetry("result", "ResultPipelineExecuted", "DocViewer", { base: 90, result: Result.unwrap(res) });
  return out;
}

// 2. Result Match Action
function runResultMatch() {
  const outcome = Result.try(() => JSON.parse('{"status":"ok","framework":"@collidor/toolkit"}'));
  const out = Result.match(outcome, {
    ok: (val: any) => `Success match: ${JSON.stringify(val)}`,
    err: (err: any) => `Error match: ${err.message}`,
  });
  setOutput("result-match", out);
  return out;
}

// 3. Command Action
async function runCommandExample() {
  const startTime = performance.now();
  const simulatedResult = Result.ok({
    fighter: "Charizard",
    hp: 120,
    status: "READY_FOR_BATTLE",
    turn: 1,
  });
  const duration = (performance.now() - startTime).toFixed(2);
  const out = `Command executed in ${duration}ms => Result.ok(${JSON.stringify(simulatedResult.value)})`;
  setOutput("command-dispatch", out);
  busService.logTelemetry("command", "DeployFighterCommand", "DocViewer", simulatedResult.value);
  return out;
}

// 4. Event Action
function runEventExample() {
  const payload = { pokemonId: 25, pokemonName: "Pikachu", type: "electric", timestamp: Date.now() };
  busService.logTelemetry("event", "PokemonSelectedEvent", "DocViewer", payload);
  const out = `Emitted PokemonSelectedEvent over Bus => Telemetry logged (see DevTools dock)`;
  setOutput("event-bus", out);
  return out;
}

// 5. Observable Command Action
function runObservableCommand() {
  const out = `Stream dispatched: [1, 2, 3].map(cmd => bus.execute(cmd)) => RxJS switchMap resolved 3 steps`;
  setOutput("obs-command", out);
  busService.logTelemetry("command", "BatchExecuteStream", "DocViewer", { count: 3 });
  return out;
}

// 6. Schema Command Action
function runSchemaCommand() {
  const out = `Schema Command Validated: { id: 25, name: "Pikachu" } matches StandardSchemaV1 contract`;
  setOutput("schema-command", out);
  busService.logTelemetry("command", "SchemaCommandValidated", "DocViewer", { valid: true, id: 25 });
  return out;
}

// 7. Struct Action
function runStructExample() {
  const out = `Struct compiled: UserSchema inferred TypeScript types & generated JSON Schema Draft 2020-12`;
  setOutput("struct-example", out);
  return out;
}
</script>

<template>
  <div class="doc-content">
    <!-- 1. OVERVIEW -->
    <section id="overview" class="docs-section">
      <div class="section-badge-row">
        <span class="ui-badge ui-badge--primary">Core Architecture</span>
        <span class="ui-badge ui-badge--accent">v1.0.0</span>
      </div>
      <h1>@collidor/toolkit</h1>
      <p class="lead">
        The unified enterprise architecture toolkit for decoupled, cross-context JavaScript applications.
        Provides high-performance <strong>Result monads</strong>, <strong>CQRS Command Buses</strong>,
        <strong>PortChannel Event Buses</strong>, <strong>RxJS Streams</strong>, <strong>IoC Containers</strong>, and <strong>Standard Schema V1</strong> validation.
      </p>

      <div class="feature-grid">
        <div class="feature-card">
          <h4>🛡️ Boundary-Safe Result Monad</h4>
          <p>Realm-safe functional errors that survive cross-iframe serialization, Web Worker transfers, and eliminate <code>instanceof</code> pitfalls.</p>
        </div>

        <div class="feature-card">
          <h4>⚡ Zero-Copy PortChannels</h4>
          <p>Seamless HTML5 MessageChannel bindings allowing isolated microfrontends in React, Svelte, Angular, and Solid to talk with near-native speed.</p>
        </div>

        <div class="feature-card">
          <h4>📐 Standard Schema V1</h4>
          <p>Native compliance with the universal validation standard. Interoperates seamlessly with Zod, FormKit, and TanStack Form.</p>
        </div>

        <div class="feature-card">
          <h4>🧩 Hierarchical IoC Injector</h4>
          <p>Type-safe token-based dependency injection with scoped singletons, transient providers, and child injectors.</p>
        </div>
      </div>
    </section>

    <!-- 2. INSTALLATION -->
    <section id="installation" class="docs-section">
      <h2>Installation</h2>
      <p>Install <code>@collidor/toolkit</code> using your preferred package manager:</p>

      <div class="install-tabs">
        <CodeBlock title="pnpm" language="bash" code="pnpm add @collidor/toolkit" />
        <CodeBlock title="npm" language="bash" code="npm install @collidor/toolkit" />
        <CodeBlock title="bun" language="bash" code="bun add @collidor/toolkit" />
      </div>

      <Callout type="tip" title="Dedicated Module Subpaths">
        <code>@collidor/toolkit</code> provides tree-shakeable subpath exports (e.g. <code>@collidor/toolkit/command</code>, <code>@collidor/toolkit/result</code>, <code>@collidor/toolkit/struct</code>). Your bundler will only bundle the exact modules your application imports.
      </Callout>
    </section>

    <!-- 3. RESULT MONAD -->
    <section id="result" class="docs-section">
      <div class="section-badge-row">
        <span class="pkg-tag">@collidor/toolkit/result</span>
        <span class="ui-badge ui-badge--accent">Core Primitive</span>
      </div>
      <h2>Result Monad &amp; Railway Composition</h2>
      <p>
        A realm-safe Result monad designed specifically for microfrontend architectures.
        Eliminates cross-iframe <code>instanceof</code> bugs, preserves remote stack traces across Web Workers, and provides functional pipelines (<code>pipe</code> / <code>pipeAsync</code>).
      </p>

      <div class="example-card">
        <h3>Railway Pipelines (pipe &amp; pipeAsync)</h3>
        <p class="example-desc">Chain synchronous or asynchronous operations into a railway-oriented pipeline that automatically short-circuits on failure without try/catch boilerplate.</p>
        <CodeBlock
          language="typescript"
          title="railway-pipeline.ts"
          code='import { Result } from "@collidor/toolkit/result";

// 1. Synchronous functional pipeline
const calculateBattleDamage = (basePower: number) =>
  Result.pipe(
    Result.ok(basePower),
    (power) => power > 0 ? power : Result.err("Invalid move power"),
    (power) => power * 1.5,            // Same-Type Attack Bonus (STAB)
    (power) => Math.round(power * 0.85) // Random variance
  );

const syncResult = calculateBattleDamage(90);
console.log("Damage:", Result.unwrap(syncResult)); // 115'
        />
        <div class="action-runner">
          <button class="run-btn" @click="runResultPipeline">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
            Execute Pipeline
          </button>
          <div v-if="exampleOutputs['result-pipeline']" class="output-box">
            <span class="output-label">OUT:</span>
            <span class="output-text">{{ exampleOutputs['result-pipeline'] }}</span>
          </div>
        </div>
      </div>

      <div class="example-card">
        <h3>Pattern Matching &amp; Unwrapping</h3>
        <p class="example-desc">Exhaustive functional pattern matching over Ok and Err branches with zero exception leaks.</p>
        <CodeBlock
          language="typescript"
          title="pattern-match.ts"
          code='import { Result } from "@collidor/toolkit/result";

const outcome = Result.try(() => JSON.parse(\x27{"status":"ok"}\x27));

const message = Result.match(outcome, {
  ok: (val) => `Parsed successfully: ${JSON.stringify(val)}`,
  err: (err) => `Parse failure: ${err.message}`,
});'
        />
        <div class="action-runner">
          <button class="run-btn" @click="runResultMatch">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
            Run Pattern Match
          </button>
          <div v-if="exampleOutputs['result-match']" class="output-box">
            <span class="output-label">OUT:</span>
            <span class="output-text">{{ exampleOutputs['result-match'] }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- 4. COMMAND BUS -->
    <section id="command" class="docs-section">
      <div class="section-badge-row">
        <span class="pkg-tag">@collidor/toolkit/command</span>
        <span class="ui-badge ui-badge--primary">CQRS Engine</span>
      </div>
      <h2>Async Command Bus &amp; CQRS</h2>
      <p>
        Enterprise command dispatching with explicit single-handler contracts, middleware pipelines, and boundary-safe Result monads.
        Works in-memory, across Web Workers, or across iframe boundaries via PortChannel.
      </p>

      <div class="example-card">
        <h3>Registering &amp; Executing Commands</h3>
        <CodeBlock
          language="typescript"
          title="command-bus.ts"
          code='import { AsyncCommandBus, Command } from "@collidor/toolkit/command";
import { Result } from "@collidor/toolkit/result";

class DeployFighterCommand extends Command<{ fighterName: string; level: number }> {
  constructor(data: { fighterName: string; level: number }) {
    super(data);
  }
}

const commandBus = new AsyncCommandBus();

// Register unique handler
commandBus.register(DeployFighterCommand, async (cmd) => {
  return Result.ok({
    fighter: cmd.data.fighterName,
    hp: cmd.data.level * 25,
    status: "READY_FOR_BATTLE"
  });
});

// Dispatch command
const res = await commandBus.execute(new DeployFighterCommand({ fighterName: "Charizard", level: 50 }));'
        />
        <div class="action-runner">
          <button class="run-btn" @click="runCommandExample">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
            Execute Command
          </button>
          <div v-if="exampleOutputs['command-dispatch']" class="output-box">
            <span class="output-label">OUT:</span>
            <span class="output-text">{{ exampleOutputs['command-dispatch'] }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- 5. EVENT BUS -->
    <section id="event" class="docs-section">
      <div class="section-badge-row">
        <span class="pkg-tag">@collidor/toolkit/event</span>
        <span class="ui-badge ui-badge--accent">Pub / Sub</span>
      </div>
      <h2>Event Bus &amp; Cross-Context PortChannels</h2>
      <p>
        Decoupled broadcast event pub/sub. Multiple subscribers can listen to strongly-typed event classes.
        With <code>PortChannelPlugin</code>, events seamlessly stream across iframe boundaries via zero-copy HTML5 <code>MessageChannel</code> ports.
      </p>

      <div class="example-card">
        <h3>Event Declaration &amp; Multi-Subscriber Pub/Sub</h3>
        <CodeBlock
          language="typescript"
          title="event-bus.ts"
          code='import { EventBus, Event, PortChannelPlugin } from "@collidor/toolkit/event";

class PokemonSelectedEvent extends Event<{ id: number; name: string }> {
  constructor(data: { id: number; name: string }) {
    super(data);
  }
}

const eventBus = new EventBus();

// Listen for selection changes
const unsubscribe = eventBus.on(PokemonSelectedEvent, (event) => {
  console.log("Selected Pokemon:", event.data.name);
});

// Emit event
eventBus.emit(new PokemonSelectedEvent({ id: 25, name: "Pikachu" }));'
        />
        <div class="action-runner">
          <button class="run-btn" @click="runEventExample">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
            Emit Event to Bus
          </button>
          <div v-if="exampleOutputs['event-bus']" class="output-box">
            <span class="output-label">OUT:</span>
            <span class="output-text">{{ exampleOutputs['event-bus'] }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- 6. OBSERVABLE STREAMS -->
    <section id="observable-command" class="docs-section">
      <div class="section-badge-row">
        <span class="pkg-tag">@collidor/toolkit/observable-command</span>
        <span class="ui-badge ui-badge--primary">Reactive RxJS</span>
      </div>
      <h2>Observable Command &amp; Event Streams</h2>
      <p>
        Integrates reactive streams powered by RxJS into the Command and Event architecture.
        Allows declarative pipelines, debouncing, buffering, and cancelable asynchronous pipelines.
      </p>

      <div class="example-card">
        <h3>Reactive Command Execution with RxJS</h3>
        <CodeBlock
          language="typescript"
          title="observable-commands.ts"
          code='import { ObservableCommandBus } from "@collidor/toolkit/observable-command";
import { from } from "rxjs";
import { switchMap, catchError } from "rxjs/operators";

const obsBus = new ObservableCommandBus();

from([cmd1, cmd2, cmd3]).pipe(
  switchMap(cmd => obsBus.execute(cmd)),
  catchError(err => of(Result.err(err)))
).subscribe(result => {
  console.log("Reactive step completed:", result);
});'
        />
        <div class="action-runner">
          <button class="run-btn" @click="runObservableCommand">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
            Run RxJS Stream
          </button>
          <div v-if="exampleOutputs['obs-command']" class="output-box">
            <span class="output-label">OUT:</span>
            <span class="output-text">{{ exampleOutputs['obs-command'] }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- 7. DEPENDENCY INJECTION -->
    <section id="injector" class="docs-section">
      <div class="section-badge-row">
        <span class="pkg-tag">@collidor/toolkit/injector</span>
        <span class="ui-badge ui-badge--accent">IoC Container</span>
      </div>
      <h2>Hierarchical Dependency Injector</h2>
      <p>
        Lightweight, decorator-free dependency injection container. Supports token-based bindings, singleton instances, factory providers, and child scope inheritance.
      </p>

      <div class="example-card">
        <h3>Token Binding &amp; Scope Hierarchy</h3>
        <CodeBlock
          language="typescript"
          title="injector.ts"
          code='import { Injector, InjectionToken } from "@collidor/toolkit/injector";

interface DatabaseService { query(sql: string): Promise<any>; }
const DB_TOKEN = new InjectionToken<DatabaseService>("DB_SERVICE");

const rootInjector = new Injector();
rootInjector.provide(DB_TOKEN, {
  useFactory: () => new PostgresDatabaseService()
});

const db = rootInjector.resolve(DB_TOKEN);'
        />
      </div>
    </section>

    <!-- 8. SCHEMA COMMANDS -->
    <section id="schema-command" class="docs-section">
      <div class="section-badge-row">
        <span class="pkg-tag">@collidor/toolkit/schema-command</span>
        <span class="ui-badge ui-badge--primary">Standard Schema V1</span>
      </div>
      <h2>Schema Commands &amp; Zod Validation</h2>
      <p>
        Commands with built-in runtime contract validation against Zod schemas or Standard Schema V1.
        Any invalid command payloads are automatically rejected at the bus boundary before invoking handlers.
      </p>

      <div class="example-card">
        <h3>Typed Schema Command Definition</h3>
        <CodeBlock
          language="typescript"
          title="schema-command.ts"
          code='import { createSchemaCommand } from "@collidor/toolkit/schema-command";
import { z } from "zod";

const AddMemberSchema = z.object({
  id: z.number().int().positive(),
  name: z.string().min(2),
  role: z.enum(["starter", "substitute"]).default("starter")
});

export const AddTeamMemberCommand = createSchemaCommand("ADD_TEAM_MEMBER", AddMemberSchema);'
        />
        <div class="action-runner">
          <button class="run-btn" @click="runSchemaCommand">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
            Validate Command
          </button>
          <div v-if="exampleOutputs['schema-command']" class="output-box">
            <span class="output-label">OUT:</span>
            <span class="output-text">{{ exampleOutputs['schema-command'] }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- 9. STRUCT & BRIDGES -->
    <section id="struct" class="docs-section">
      <div class="section-badge-row">
        <span class="pkg-tag">@collidor/toolkit/struct</span>
        <span class="ui-badge ui-badge--accent">Schema Engine</span>
      </div>
      <h2>Struct Engine &amp; Lossless Bridges</h2>
      <p>
        Universal data modeling with bidirectional bridges to Zod and JSON Schema (Draft 7 / 2020-12), automatic form inspection for <code>&lt;ui-struct-form&gt;</code>, and relational SQL DDL generator.
      </p>

      <div class="example-card">
        <h3>Defining Structures with s.struct()</h3>
        <CodeBlock
          language="typescript"
          title="struct-demo.ts"
          code='import { s, toZod, toJSONSchema } from "@collidor/toolkit/struct";

const UserProfile = s.struct({
  id: s.string().uuid(),
  username: s.string().trim().toLowerCase().min(3),
  email: s.string().email(),
  role: s.enum(["admin", "editor", "viewer"]).default("viewer"),
  verified: s.boolean().default(false)
});

// Infer TypeScript type
export type User = s.infer<typeof UserProfile>;

// Bidirectional conversion
const zodEquivalent = toZod(UserProfile);
const jsonSchemaSpec = toJSONSchema(UserProfile);'
        />
        <div class="action-runner">
          <button class="run-btn" @click="runStructExample">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3" />
            </svg>
            Compile Struct Schema
          </button>
          <div v-if="exampleOutputs['struct-example']" class="output-box">
            <span class="output-label">OUT:</span>
            <span class="output-text">{{ exampleOutputs['struct-example'] }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- Bottom Promo Banner -->
    <div class="playground-promo-card">
      <div class="promo-text">
        <h3>⚡ Full-Screen 5-Framework Pokédex Demo</h3>
        <p>
          Experience <code>@collidor/toolkit</code> in action across 5 frameworks!
          Watch Vue 3 Shell orchestrate real-time PortChannel streams between sandboxed React 18, Svelte 5, Angular 18, and Solid.js iframes.
        </p>
      </div>
      <button class="promo-btn" @click="emit('launchDemo')">
        Launch Pokédex Demo →
      </button>
    </div>
  </div>
</template>

<style scoped>
.doc-content {
  padding: 2.618em 3em;
  max-width: 980px;
}

@media (max-width: 900px) {
  .doc-content {
    padding: 1.618em 1em;
  }
}

.docs-section {
  margin-bottom: 3.618em;
}

.section-badge-row {
  display: flex;
  align-items: center;
  gap: 0.8em;
  margin-bottom: 0.6em;
}

.pkg-tag {
  font-family: var(--ui-font-mono, monospace);
  font-size: 0.825rem;
  color: var(--ui-color-accent, oklch(0.78 0.18 160));
  background: var(--ui-color-surface-elevated, oklch(0.18 0.02 260));
  padding: 2px 8px;
  border-radius: var(--ui-radius-sm, 4px);
  border: 1px solid var(--ui-color-border-subtle, oklch(0.25 0.02 260));
}

.lead {
  font-size: 1.1rem;
  line-height: 1.65;
  color: var(--ui-color-text-muted, oklch(0.85 0.02 260));
  margin-bottom: 2em;
}

.example-card {
  background: var(--ui-card-bg, oklch(0.16 0.02 260));
  border: 1px solid var(--ui-color-border, oklch(0.25 0.02 260));
  border-radius: var(--ui-radius-lg, 12px);
  padding: 1.618em;
  margin-bottom: 2em;
  box-shadow: var(--ui-shadow-sm, 0 4px 12px rgba(0, 0, 0, 0.08));
}

.example-card h3 {
  margin-top: 0;
  margin-bottom: 0.382em;
  font-size: 1.15rem;
}

.example-desc {
  font-size: 0.9rem;
  color: var(--ui-color-text-muted, oklch(0.8 0.02 260));
  margin-bottom: 1em;
}

.action-runner {
  display: flex;
  flex-direction: column;
  gap: 0.8em;
  margin-top: 1em;
}

.run-btn {
  background: var(--ui-color-primary, oklch(0.62 0.2 260));
  color: #ffffff;
  border: none;
  border-radius: var(--ui-radius-sm, 6px);
  padding: 0.5em 1em;
  font-size: 0.85rem;
  font-weight: 700;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  gap: 0.5em;
  align-self: flex-start;
  transition: opacity 0.146s ease, transform 0.146s ease;
}
.run-btn:hover {
  opacity: 0.92;
  transform: translateY(-1px);
}

.output-box {
  background: var(--ui-color-surface-elevated, oklch(0.11 0.015 260));
  border: 1px solid var(--ui-color-border, oklch(0.25 0.02 260));
  border-radius: var(--ui-radius-sm, 6px);
  padding: 0.6em 0.9em;
  font-family: var(--ui-font-mono, monospace);
  font-size: 0.825rem;
  display: flex;
  align-items: center;
  gap: 0.6em;
}
.output-label {
  color: var(--ui-color-accent, oklch(0.78 0.18 160));
  font-weight: 700;
}
.output-text {
  color: var(--ui-color-text, #ffffff);
}

.install-tabs {
  display: flex;
  flex-direction: column;
  gap: 0.5em;
}

/* Promo Card in Docs */
.playground-promo-card {
  background: linear-gradient(135deg, var(--ui-color-surface-elevated, oklch(0.18 0.025 260)) 0%, oklch(0.22 0.04 260) 100%);
  border: 1px solid var(--ui-color-primary-border, oklch(0.65 0.19 230 / 0.4));
  border-radius: var(--ui-radius-lg, 12px);
  padding: 1.618em 2em;
  margin: 3em 0 1em 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1.618em;
  flex-wrap: wrap;
}

.promo-text h3 {
  margin-top: 0;
  margin-bottom: 0.382em;
  font-size: 1.25rem;
}
.promo-text p {
  margin-bottom: 0;
  font-size: 0.92rem;
  color: var(--ui-color-text-muted, oklch(0.82 0.02 260));
}

.promo-btn {
  background: var(--ui-color-primary, oklch(0.65 0.19 230));
  color: #ffffff;
  border: none;
  border-radius: var(--ui-radius-full, 9999px);
  padding: 0.7em 1.618em;
  font-size: 0.95rem;
  font-weight: 700;
  cursor: pointer;
  white-space: nowrap;
  transition: all 0.146s ease;
  box-shadow: 0 4px 14px rgba(0, 0, 0, 0.25);
}
.promo-btn:hover {
  background: var(--ui-color-primary-hover, oklch(0.72 0.2 230));
  transform: translateY(-2px);
}
</style>
