// demo/svelte/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import {
    FetchPokemonDetailCommand,
    PokemonSelectedEvent,
    PokemonInspectedEvent,
    DeployToBattleCommand,
    SEED_POKEMON_LIST,
    AddTeamMemberSchemaCommand,
  } from "@demo/shared";
  import type { PokemonDetail } from "@demo/shared";
  import { Result } from "@collidor/result";

  export let busService: any;

  let currentPokemon: PokemonDetail = SEED_POKEMON_LIST[3]; // Pikachu default
  let isLoading = false;
  let statusMessage: string | null = null;
  let isErrorMessage = false;
  let unsubs: Array<() => void> = [];

  onMount(() => {
    const handleLoadPokemon = async (pokemon: any) => {
      if (!pokemon?.id) return;
      isLoading = true;
      try {
        const res = await busService.commandBus.execute(
          new FetchPokemonDetailCommand({ idOrName: pokemon.id })
        );

        if (Result.isResult(res) && res.success) {
          currentPokemon = res.value;
        } else if (!res.success) {
          console.error("Failed to fetch detail:", res.error);
        }
      } catch (err) {
        console.error("Command execution error:", err);
      } finally {
        isLoading = false;
      }
    };

    const unsubSelect = busService.eventBus.on(PokemonSelectedEvent, handleLoadPokemon);
    const unsubInspect = busService.eventBus.on(PokemonInspectedEvent, handleLoadPokemon);

    unsubs.push(unsubSelect, unsubInspect);
  });

  onDestroy(() => {
    unsubs.forEach((u) => u());
  });

  async function handleAddToTeam() {
    isErrorMessage = false;
    statusMessage = "Adding to Angular Team via SchemaCommand...";
    try {
      const res = await busService.commandBus.execute(
        new AddTeamMemberSchemaCommand({
          pokemon: currentPokemon,
          level: 50,
        })
      );

      if (res && res.success) {
        statusMessage = `✓ ${currentPokemon.name} added to party!`;
      } else {
        isErrorMessage = true;
        statusMessage = `⚠ ${res?.message || "Failed to add to team"}`;
      }
    } catch (err: any) {
      isErrorMessage = true;
      statusMessage = `⚠ Command Error: ${err.message || String(err)}`;
    }

    setTimeout(() => {
      statusMessage = null;
      isErrorMessage = false;
    }, 3500);
  }

  async function handleDeployToBattle() {
    isErrorMessage = false;
    statusMessage = `Deploying ${currentPokemon.name} to Battle Arena...`;
    try {
      const res = await busService.commandBus.execute(
        new DeployToBattleCommand({ pokemon: currentPokemon })
      );
      if (Result.isResult(res) && res.success) {
        statusMessage = `⚔️ ${currentPokemon.name} deployed to Battle Arena!`;
      } else {
        isErrorMessage = true;
        statusMessage = `⚠ Deploy failed: ${res?.error || "Unknown error"}`;
      }
    } catch (err: any) {
      isErrorMessage = true;
      statusMessage = `⚠ Command Error: ${err.message || String(err)}`;
    }

    setTimeout(() => {
      statusMessage = null;
      isErrorMessage = false;
    }, 3500);
  }
</script>

<div class="svelte-root">
  <!-- Top bar -->
  <div class="header-bar">
    <span class="title">
      <span class="dot"></span>
      Svelte 5 Reactive Inspector
    </span>
    {#if isLoading}
      <span class="loading-tag">Loading via CommandBus...</span>
    {/if}
  </div>

  <!-- Hero Card -->
  <div class="hero-card">
    {#if statusMessage}
      <div class="toast {isErrorMessage ? 'toast-err' : 'toast-ok'}">
        {statusMessage}
      </div>
    {/if}

    <div class="art-container">
      <div class="glow"></div>
      <img
        src={currentPokemon.sprites.artwork}
        alt={currentPokemon.name}
        class="artwork"
      />
      <img
        src={currentPokemon.sprites.showdownFront}
        alt="{currentPokemon.name} showdown"
        class="showdown"
      />
    </div>

    <span class="id-tag">#{currentPokemon.id.toString().padStart(3, "0")}</span>
    <h3 class="name">{currentPokemon.name}</h3>
    <p class="genus">{currentPokemon.species.genus}</p>

    <!-- Type Pills -->
    <div class="types-row">
      {#each currentPokemon.types as t}
        <span class="type-badge type-{t}">{t}</span>
      {/each}
    </div>

    <!-- Action Buttons -->
    <div class="actions-grid">
      <button on:click={handleAddToTeam} class="btn-team" title="Send to Angular Team Builder via SchemaCommand">
        <span>+ Add to Team</span>
        <span class="subtext">Angular Microfrontend</span>
      </button>

      <button on:click={handleDeployToBattle} class="btn-battle" title="Deploy directly to Solid Battle Arena">
        <span>⚔️ Deploy Arena</span>
        <span class="subtext">Solid.js Microfrontend</span>
      </button>
    </div>

    <!-- Flavor Text -->
    <p class="flavor-text">
      "{currentPokemon.species.flavorText}"
    </p>

    <!-- Stats Bars -->
    <div class="stats-box">
      <div class="stat-line">
        <span>HP</span>
        <span class="val">{currentPokemon.stats.hp}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill hp" style="width: {Math.min(100, (currentPokemon.stats.hp / 150) * 100)}%"></div>
      </div>

      <div class="stat-line pt">
        <span>Attack</span>
        <span class="val">{currentPokemon.stats.attack}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill atk" style="width: {Math.min(100, (currentPokemon.stats.attack / 150) * 100)}%"></div>
      </div>

      <div class="stat-line pt">
        <span>Defense</span>
        <span class="val">{currentPokemon.stats.defense}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill def" style="width: {Math.min(100, (currentPokemon.stats.defense / 150) * 100)}%"></div>
      </div>

      <div class="stat-line pt">
        <span>Speed</span>
        <span class="val">{currentPokemon.stats.speed}</span>
      </div>
      <div class="bar-track">
        <div class="bar-fill spd" style="width: {Math.min(100, (currentPokemon.stats.speed / 150) * 100)}%"></div>
      </div>
    </div>

    <!-- Moves List preview -->
    <div class="moves-box">
      <span class="moves-label">Combat Moves</span>
      <div class="moves-row">
        {#each currentPokemon.moves.slice(0, 4) as m}
          <span class="move-pill">{m.name}</span>
        {/each}
      </div>
    </div>
  </div>
</div>

<style>
  :global(:root) {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color-scheme: dark;
  }
  :global(html), :global(body) {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    background: #090d16;
    color: #f1f5f9;
    font-size: 13px;
    overflow-x: hidden;
  }
  :global(body.light), :global(html.light body) {
    background: #f8fafc;
    color: #0f172a;
  }
  * { box-sizing: border-box; }

  .svelte-root {
    display: flex;
    flex-direction: column;
    height: 100%;
    padding: 8px;
    box-sizing: border-box;
    overflow-y: auto;
  }
  .header-bar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-bottom: 6px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.08);
    margin-bottom: 8px;
    font-size: 11px;
  }
  .title {
    font-weight: 700;
    color: #fb923c;
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: #fb923c;
    box-shadow: 0 0 8px #fb923c;
  }
  .loading-tag {
    font-size: 10px;
    color: #f43f5e;
    animation: pulse 1.5s infinite;
  }

  .hero-card {
    background: rgba(15, 23, 42, 0.5);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 12px;
    padding: 12px;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    position: relative;
  }

  .toast {
    position: absolute;
    top: 8px;
    left: 8px;
    right: 8px;
    padding: 6px 10px;
    border-radius: 6px;
    font-size: 11px;
    font-weight: 600;
    z-index: 20;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
  }
  .toast-ok { background: #059669; color: #ffffff; }
  .toast-err { background: #e11d48; color: #ffffff; }

  .art-container {
    position: relative;
    width: 120px;
    height: 120px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 4px;
  }
  .glow {
    position: absolute;
    inset: 0;
    background: radial-gradient(circle, rgba(251, 146, 60, 0.2) 0%, transparent 70%);
    border-radius: 50%;
  }
  .artwork {
    width: 110px;
    height: 110px;
    object-fit: contain;
    position: relative;
    z-index: 2;
    filter: drop-shadow(0 6px 12px rgba(0, 0, 0, 0.4));
  }
  .showdown {
    position: absolute;
    bottom: -2px;
    right: -2px;
    width: 38px;
    height: 38px;
    object-fit: contain;
    z-index: 3;
    filter: drop-shadow(0 2px 4px rgba(0, 0, 0, 0.5));
  }

  .id-tag {
    font-size: 10px;
    font-family: monospace;
    color: #64748b;
  }
  .name {
    margin: 2px 0;
    font-size: 16px;
    font-weight: 800;
    text-transform: capitalize;
    color: #ffffff;
  }
  .genus {
    margin: 0 0 6px 0;
    font-size: 11px;
    color: #94a3b8;
  }

  .types-row {
    display: flex;
    gap: 4px;
    margin-bottom: 10px;
  }

  /* Badges */
  :global(.type-badge) {
    display: inline-block;
    font-size: 9px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 2px 7px;
    border-radius: 9999px;
    color: #ffffff;
    text-shadow: 0 1px 2px rgba(0,0,0,0.5);
  }
  :global(.type-normal) { background: #9fa19f; }
  :global(.type-fire) { background: #e62829; }
  :global(.type-water) { background: #2980ef; }
  :global(.type-grass) { background: #3fa129; }
  :global(.type-electric) { background: #fac000; color: #1e293b; text-shadow: none; }
  :global(.type-ice) { background: #3dcef3; color: #0f172a; text-shadow: none; }
  :global(.type-fighting) { background: #ff8000; }
  :global(.type-poison) { background: #9141cb; }
  :global(.type-ground) { background: #915121; }
  :global(.type-flying) { background: #81b9ef; color: #0f172a; text-shadow: none; }
  :global(.type-psychic) { background: #ef4179; }
  :global(.type-bug) { background: #91a119; }
  :global(.type-rock) { background: #afa981; }
  :global(.type-ghost) { background: #704170; }
  :global(.type-dragon) { background: #5060e1; }
  :global(.type-steel) { background: #60a1b8; }
  :global(.type-fairy) { background: #ef70ef; }

  .actions-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
    width: 100%;
    margin-bottom: 10px;
  }
  .btn-team, .btn-battle {
    padding: 8px 6px;
    border-radius: 8px;
    border: none;
    cursor: pointer;
    font-size: 11px;
    font-weight: 700;
    color: #ffffff;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 2px;
    transition: transform 0.1s ease, filter 0.1s ease;
  }
  .btn-team {
    background: linear-gradient(135deg, #f97316, #e11d48);
    box-shadow: 0 2px 8px rgba(249, 115, 22, 0.3);
  }
  .btn-battle {
    background: linear-gradient(135deg, #06b6d4, #2563eb);
    box-shadow: 0 2px 8px rgba(6, 182, 212, 0.3);
  }
  .btn-team:hover, .btn-battle:hover { filter: brightness(1.1); transform: translateY(-1px); }
  .btn-team:active, .btn-battle:active { transform: translateY(0); }
  .subtext {
    font-size: 9px;
    opacity: 0.85;
    font-weight: 500;
  }

  .flavor-text {
    font-size: 11px;
    color: #cbd5e1;
    font-style: italic;
    background: rgba(0, 0, 0, 0.25);
    padding: 8px 10px;
    border-radius: 6px;
    border: 1px solid rgba(255, 255, 255, 0.05);
    text-align: left;
    width: 100%;
    margin: 0 0 10px 0;
  }

  .stats-box {
    width: 100%;
    font-family: monospace;
    font-size: 10px;
    text-align: left;
    margin-bottom: 10px;
  }
  .stat-line {
    display: flex;
    justify-content: space-between;
    color: #94a3b8;
    margin-bottom: 2px;
  }
  .stat-line.pt { margin-top: 4px; }
  .val { font-weight: 700; color: #ffffff; }
  .bar-track {
    width: 100%;
    height: 4px;
    background: rgba(255, 255, 255, 0.1);
    border-radius: 9999px;
    overflow: hidden;
  }
  .bar-fill { height: 100%; border-radius: 9999px; transition: width 0.4s ease; }
  .bar-fill.hp { background: #34d399; }
  .bar-fill.atk { background: #f43f5e; }
  .bar-fill.def { background: #38bdf8; }
  .bar-fill.spd { background: #fbbf24; }

  .moves-box {
    width: 100%;
    text-align: left;
  }
  .moves-label {
    font-size: 9px;
    text-transform: uppercase;
    font-weight: 700;
    color: #64748b;
    display: block;
    margin-bottom: 4px;
  }
  .moves-row {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
  }
  .move-pill {
    padding: 2px 6px;
    border-radius: 4px;
    background: rgba(255, 255, 255, 0.08);
    font-size: 10px;
    font-family: monospace;
    color: #cbd5e1;
    text-transform: capitalize;
  }

  @keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  }
</style>

// demo/angular/src/app/app.component.ts
import { Component, ChangeDetectionStrategy, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { TeamService } from "./services/team.service";
import { SEED_POKEMON_LIST, TeamMember } from "@demo/shared";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class.light]": 'theme() === "light"',
  },
  template: `
    <div class="team-container" [class.light]="theme() === 'light'">
      <!-- Top Bar -->
      <div class="header-bar">
        <div>
          <h2 class="title">
            <span class="dot"></span>
            Angular 18 Team Builder (Analog)
          </h2>
          <p class="subtitle">Sandboxed Iframe &bull; Schema-Validated Commands</p>
        </div>
        <div class="status-badge" [class.connected]="isConnected()">
          {{ isConnected() ? '⚡ PortChannel Connected' : 'Waiting for Handshake...' }}
        </div>
      </div>

      <!-- Team Roster Header -->
      <div class="roster-header">
        <span class="party-count">
          Party: <strong>{{ team().members.length }}</strong> / 6 Pokémon
        </span>
        <div class="actions">
          <button (click)="quickAddStarter()" class="btn-sm btn-starter" [disabled]="team().members.length >= 6">
            + Quick Add
          </button>
          <button (click)="clearTeam()" class="btn-sm btn-clear" [disabled]="team().members.length === 0">
            Clear
          </button>
        </div>
      </div>

      <!-- Members Grid -->
      <div class="roster-grid">
        @for (member of team().members; track member.instanceId) {
          <div class="member-card">
            <div class="member-left" (click)="inspectMember(member)" title="Inspect this Pokémon in Svelte & Vue">
              <img [src]="member.pokemon.sprites.thumbnail" [alt]="member.pokemon.name" class="member-img" />
              <div>
                <div class="member-title">
                  <span class="name">{{ member.nickname || member.pokemon.name }}</span>
                  <span class="level">Lv. {{ member.level }}</span>
                </div>
                <div class="types-row">
                  @for (t of member.pokemon.types; track t) {
                    <span class="type-pill" [class]="'type-' + t">{{ t }}</span>
                  }
                </div>
              </div>
            </div>

            <div class="member-right">
              <button (click)="deployToBattle(member, $event)" class="btn-action-battle" title="Deploy to Solid Battle Arena">
                ⚔️ Arena
              </button>
              <button (click)="removeMember(member.instanceId, $event)" class="btn-remove" title="Remove member">
                &times;
              </button>
            </div>
          </div>
        } @empty {
          <div class="empty-state">
            <p>Your team is currently empty.</p>
            <p class="empty-hint">
              Select any Pokémon in the Vue catalog or Svelte inspector, then click <strong>"+ Add to Team"</strong>!
            </p>
          </div>
        }
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: block;
      height: 100%;
      min-height: 100%;
      font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
      color: #f8fafc;
      background-color: #090d16;
      box-sizing: border-box;
      padding: 12px;
      overflow-y: auto;
      transition: background-color 0.2s, color 0.2s;
    }

    :host(.light),
    :host-context(html.light),
    :host-context(body.light) {
      background-color: #f8fafc !important;
      color: #0f172a !important;
    }

    .team-container {
      display: flex;
      flex-direction: column;
      gap: 12px;
      min-height: 100%;
    }

    .header-bar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid rgba(255, 255, 255, 0.08);
      padding-bottom: 8px;
    }

    .title {
      font-size: 13px;
      font-weight: 800;
      color: #f87171;
      display: flex;
      align-items: center;
      gap: 6px;
      margin: 0;
    }

    .dot {
      width: 8px;
      height: 8px;
      border-radius: 9999px;
      background-color: #ef4444;
      display: inline-block;
    }

    .subtitle {
      font-size: 10px;
      color: #94a3b8;
      margin: 2px 0 0 0;
    }

    .status-badge {
      font-size: 10px;
      font-family: 'JetBrains Mono', monospace;
      padding: 2px 8px;
      border-radius: 6px;
      background: rgba(239, 68, 68, 0.1);
      border: 1px solid rgba(239, 68, 68, 0.3);
      color: #fca5a5;
    }

    .status-badge.connected {
      background: rgba(34, 197, 94, 0.1);
      border-color: rgba(34, 197, 94, 0.3);
      color: #86efac;
    }

    .roster-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 11px;
      color: #94a3b8;
    }

    .actions {
      display: flex;
      gap: 6px;
    }

    .btn-sm {
      padding: 3px 8px;
      border-radius: 6px;
      font-size: 10px;
      font-weight: 700;
      cursor: pointer;
      border: 1px solid transparent;
      transition: all 0.2s;
    }

    .btn-starter {
      background: rgba(239, 68, 68, 0.2);
      border-color: rgba(239, 68, 68, 0.4);
      color: #fca5a5;
    }
    .btn-starter:hover:not(:disabled) {
      background: rgba(239, 68, 68, 0.3);
    }

    .btn-clear {
      background: rgba(255, 255, 255, 0.05);
      border-color: rgba(255, 255, 255, 0.1);
      color: #94a3b8;
    }
    .btn-clear:hover:not(:disabled) {
      color: #f87171;
    }

    .btn-sm:disabled {
      opacity: 0.4;
      cursor: not-allowed;
    }

    .roster-grid {
      display: flex;
      flex-direction: column;
      gap: 8px;
    }

    .member-card {
      display: flex;
      align-items: center;
      justify-content: space-between;
      background: rgba(15, 23, 42, 0.8);
      border: 1px solid rgba(255, 255, 255, 0.06);
      border-radius: 10px;
      padding: 6px 10px;
      transition: border-color 0.2s;
    }
    .member-card:hover {
      border-color: rgba(239, 68, 68, 0.4);
    }

    .member-left {
      display: flex;
      align-items: center;
      gap: 10px;
      cursor: pointer;
      flex: 1;
      padding: 2px 4px;
      border-radius: 6px;
      transition: background 0.15s;
    }
    .member-left:hover {
      background: rgba(255, 255, 255, 0.05);
    }

    .member-right {
      display: flex;
      align-items: center;
      gap: 6px;
    }

    .btn-action-battle {
      background: rgba(6, 182, 212, 0.15);
      border: 1px solid rgba(6, 182, 212, 0.35);
      color: #67e8f9;
      font-size: 10px;
      font-weight: 700;
      padding: 3px 8px;
      border-radius: 6px;
      cursor: pointer;
      transition: all 0.2s;
    }
    .btn-action-battle:hover {
      background: rgba(6, 182, 212, 0.25);
      border-color: rgba(6, 182, 212, 0.6);
      color: #a5f3fc;
      transform: scale(1.03);
    }

    .member-img {
      width: 36px;
      height: 36px;
      object-fit: contain;
    }

    .member-title {
      display: flex;
      align-items: baseline;
      gap: 6px;
    }

    .name {
      font-size: 12px;
      font-weight: 700;
      text-transform: capitalize;
    }

    .level {
      font-size: 10px;
      font-family: 'JetBrains Mono', monospace;
      color: #94a3b8;
    }

    .types-row {
      display: flex;
      gap: 4px;
      margin-top: 2px;
    }

    .type-pill {
      font-size: 9px;
      font-weight: 600;
      text-transform: uppercase;
      padding: 1px 5px;
      border-radius: 4px;
    }

    .type-grass { background: rgba(34, 197, 94, 0.2); color: #4ade80; }
    .type-fire { background: rgba(239, 68, 68, 0.2); color: #f87171; }
    .type-water { background: rgba(59, 130, 246, 0.2); color: #60a5fa; }
    .type-electric { background: rgba(234, 179, 8, 0.2); color: #facc15; }
    .type-poison { background: rgba(168, 85, 247, 0.2); color: #c084fc; }
    .type-ghost { background: rgba(99, 102, 241, 0.2); color: #818cf8; }
    .type-normal { background: rgba(148, 163, 184, 0.2); color: #cbd5e1; }
    .type-dragon { background: rgba(79, 70, 229, 0.2); color: #a5b4fc; }

    .btn-remove {
      background: transparent;
      border: none;
      color: #64748b;
      font-size: 16px;
      cursor: pointer;
      padding: 4px 8px;
      border-radius: 4px;
      transition: color 0.2s;
    }
    .btn-remove:hover {
      color: #ef4444;
      background: rgba(239, 68, 68, 0.1);
    }

    .empty-state {
      text-align: center;
      padding: 24px 12px;
      border: 1px dashed rgba(255, 255, 255, 0.1);
      border-radius: 12px;
      color: #64748b;
      font-size: 11px;
    }
    .empty-hint {
      margin-top: 6px;
      font-size: 10px;
      color: #94a3b8;
    }

    /* Light Theme Direct & Context Rules */
    .team-container.light,
    :host-context(html.light) .team-container {
      background: transparent !important;
      color: #0f172a;
    }
    .team-container.light .member-card,
    :host-context(html.light) .member-card {
      background: #ffffff !important;
      border: 1px solid #e2e8f0 !important;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.04) !important;
    }
    .team-container.light .name,
    :host-context(html.light) .name {
      color: #0f172a !important;
    }
    .team-container.light .subtitle,
    :host-context(html.light) .subtitle {
      color: #475569 !important;
    }
    .team-container.light .title,
    :host-context(html.light) .title {
      color: #b91c1c !important;
    }
    .team-container.light .party-count,
    :host-context(html.light) .party-count {
      color: #1e293b !important;
    }
    .team-container.light .level,
    :host-context(html.light) .level {
      color: #475569 !important;
    }
    .team-container.light .stat-box,
    :host-context(html.light) .stat-box {
      background: #f1f5f9 !important;
      border: 1px solid #e2e8f0 !important;
    }
    .team-container.light .stat-label,
    :host-context(html.light) .stat-label {
      color: #64748b !important;
    }
    .team-container.light .stat-val,
    :host-context(html.light) .stat-val {
      color: #0f172a !important;
    }
    .team-container.light .empty-state,
    :host-context(html.light) .empty-state {
      background: #ffffff !important;
      border: 1px dashed #cbd5e1 !important;
      color: #64748b !important;
    }
    .team-container.light .empty-hint,
    :host-context(html.light) .empty-hint {
      color: #475569 !important;
    }
    .team-container.light .member-img,
    :host-context(html.light) .member-img {
      background: #f1f5f9 !important;
      border: 1px solid #e2e8f0 !important;
    }
    .team-container.light .btn-arena,
    :host-context(html.light) .btn-arena {
      background: #e0f2fe !important;
      border: 1px solid #7dd3fc !important;
      color: #0369a1 !important;
      font-weight: 700 !important;
    }
    .team-container.light .btn-arena:hover,
    :host-context(html.light) .btn-arena:hover {
      background: #bae6fd !important;
    }
    .team-container.light .btn-starter,
    :host-context(html.light) .btn-starter {
      background: #fee2e2 !important;
      border: 1px solid #fca5a5 !important;
      color: #991b1b !important;
      font-weight: 700 !important;
    }
    .team-container.light .status-badge,
    :host-context(html.light) .status-badge {
      background: #f1f5f9 !important;
      border: 1px solid #cbd5e1 !important;
      color: #475569 !important;
    }
    .team-container.light .status-badge.connected,
    :host-context(html.light) .status-badge.connected {
      background: #dcfce7 !important;
      border: 1px solid #86efac !important;
      color: #166534 !important;
      font-weight: 700 !important;
    }
    .team-container.light .btn-clear,
    :host-context(html.light) .btn-clear {
      background: #f1f5f9 !important;
      border: 1px solid #cbd5e1 !important;
      color: #475569 !important;
    }
  `],
})
export class AppComponent {
  private readonly teamService = inject(TeamService);

  readonly team = this.teamService.team;
  readonly isConnected = this.teamService.isConnected;
  readonly theme = this.teamService.theme;

  inspectMember(member: TeamMember) {
    this.teamService.selectMember(member);
  }

  deployToBattle(member: TeamMember, event: MouseEvent) {
    event.stopPropagation();
    this.teamService.deployToBattle(member);
  }

  removeMember(instanceId: string, event?: MouseEvent) {
    event?.stopPropagation();
    this.teamService.removeMember(instanceId);
  }

  clearTeam() {
    this.teamService.clearTeam();
  }

  quickAddStarter() {
    const starter = SEED_POKEMON_LIST[Math.floor(Math.random() * SEED_POKEMON_LIST.length)];
    this.teamService.addMember(starter);
  }
}
